### PR TITLE
Fix build on GCC 7, close #203

### LINKED ISSUE #203: Compiling issue
~~~~
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GCC 7.3
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- Found CAF
-- Found CAF's OpenSSL module, enabling OpenSSL support

====================|  Build Summary  |====================

Version:          0.1

Source directory: /home/adulau/git/vast
Build directory:  /home/adulau/git/vast/build
Install prefix:   /usr/local

Build type:       RelWithDebInfo
Log level:        debug
Show time report: no
Assertions:       yes
AddressSanitizer: no
gcov:             no

CC:               /usr/bin/cc
CXX:              /usr/bin/c++
CXXFLAGS:          -std=c++17 -Wall -Wextra -pedantic -ftemplate-depth=512 -ftemplate-backtrace-limit=3 -Wno-maybe-uninitialized -O2 -g -fno-omit-frame-pointer
LDFLAGS:          

CAF:              /usr/include
Snappy            no
PCAP:             /usr/include
Gperftools:       no
Doxygen:          no
md2man:           no

tcmalloc:         no
OpenCL:           no
OpenSSL:          yes

===========================================================

-- Configuring done
-- Generating done
-- Build files have been written to: /home/adulau/git/vast/build
~~~~

~~~~
[  1%] Building CXX object libvast/CMakeFiles/libvast.dir/src/address.cpp.o
In file included from /home/adulau/git/vast/libvast/src/address.cpp:25:0:
/home/adulau/git/vast/libvast/vast/json.hpp: In function ‘bool vast::convert(bool, vast::json&)’:
/home/adulau/git/vast/libvast/vast/json.hpp:166:22: error: no match for ‘operator=’ (operand types are ‘vast::json’ and ‘bool’)
   j = json::boolean{b};
                      ^
/home/adulau/git/vast/libvast/vast/json.hpp:32:7: note: candidate: vast::json& vast::json::operator=(const vast::json&)
 class json : detail::totally_ordered<json> {
       ^~~~
/home/adulau/git/vast/libvast/vast/json.hpp:32:7: note:   no known conversion for argument 1 from ‘bool’ to ‘const vast::json&’
/home/adulau/git/vast/libvast/vast/json.hpp:32:7: note: candidate: vast::json& vast::json::operator=(vast::json&&)
/home/adulau/git/vast/libvast/vast/json.hpp:32:7: note:   no known conversion for argument 1 from ‘bool’ to ‘vast::json&&’
/home/adulau/git/vast/libvast/src/address.cpp: In function ‘bool vast::convert(const vast::address&, vast::json&)’:
/home/adulau/git/vast/libvast/src/address.cpp:160:18: error: no match for ‘operator=’ (operand types are ‘vast::json’ and ‘std::enable_if_t<true, std::__cxx11::basic_string<char> > {aka std::__cxx11::basic_string<char>}’)
   j = to_string(a);
                  ^
In file included from /home/adulau/git/vast/libvast/src/address.cpp:25:0:
/home/adulau/git/vast/libvast/vast/json.hpp:32:7: note: candidate: vast::json& vast::json::operator=(const vast::json&)
 class json : detail::totally_ordered<json> {
       ^~~~
/home/adulau/git/vast/libvast/vast/json.hpp:32:7: note:   no known conversion for argument 1 from ‘std::enable_if_t<true, std::__cxx11::basic_string<char> > {aka std::__cxx11::basic_string<char>}’ to ‘const vast::json&’
/home/adulau/git/vast/libvast/vast/json.hpp:32:7: note: candidate: vast::json& vast::json::operator=(vast::json&&)
/home/adulau/git/vast/libvast/vast/json.hpp:32:7: note:   no known conversion for argument 1 from ‘std::enable_if_t<true, std::__cxx11::basic_string<char> > {aka std::__cxx11::basic_string<char>}’ to ‘vast::json&&’
libvast/CMakeFiles/libvast.dir/build.make:62: recipe for target 'libvast/CMakeFiles/libvast.dir/src/address.cpp.o' failed
make[3]: *** [libvast/CMakeFiles/libvast.dir/src/address.cpp.o] Error 1
make[3]: Leaving directory '/home/adulau/git/vast/build'
CMakeFiles/Makefile2:1166: recipe for target 'libvast/CMakeFiles/libvast.dir/all' failed
make[2]: *** [libvast/CMakeFiles/libvast.dir/all] Error 2
make[2]: Leaving directory '/home/adulau/git/vast/build'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/adulau/git/vast/build'
.Makefile.GNU:8: recipe for target 'all' failed
make: *** [all] Error 2
~~~~

Any ideas why the compilation failed?

### PR DESCRIPTION
**Pull request by Neverlord**

### CODE REVIEW

File: libvast/test/json.cpp [hunk 1]
```diff
@@ -155,16 +155,15 @@ TEST(printable) {
...
   MESSAGE("tree policy");
-  o = {
-    {"baz", 4.2},
-    {"x", a},
-    {"inner", json::object{{"a", false}, {"c", a}, {"b", 42}}}
-  };
+  o = {{"baz", json{4.2}},
+       {"x", json{a}},
+       {"inner", json{json::object{
+                   {"a", json{false}}, {"c", json{a}}, {"b", json{42}}}}}};
```
Comment (mavam) [inline libvast/test/json.cpp]: Formatting it like "actual" JSON looks a bit nicer:
```
  o = {
    {"baz", json{4.2}},
    {"x", json{a}},
    {"inner", json{json::object{
      {"a", json{false}},
      {"c", json{a}},
      {"b", json{42}}
     ...
```

File: libvast/vast/json.hpp [hunk 2]
```diff
@@ -101,69 +100,60 @@ class json : detail::totally_ordered<json> {
...
-template <>
-struct jsonize_helper<caf::none_t> {
-  using type = json::null;
-};
+template <class T,
+         int = std::is_convertible_v<T, json::number>
+               && !std::is_same_v<T, json::boolean>
+               ? 1
+               : (std::is_convertible_v<T, std::string> ? 2 : 0)>
+struct jsonize_helper;
```
Comment (mavam) [inline libvast/vast/json.hpp]: I find this formatting a bit more readable:
```
template <
  class T,
  int = std::is_convertible_v<T, json::number>
        && !std::is_same_v<T, json::boolean>
        ? 1
        : (std::is_convertible_v<T, std::string> ? 2 : 0)
>
```
But you can leave it as-is, just indent the line starting with `int` by one space.

**Comment by Neverlord** [comment]
@mavam thanks for the comments. I've followed your advice in both cases.
